### ISSUE TITLE
Mod Messages ignore user blacklist

### ISSUE THREAD

**Issue by GrumpyBear57** [LiveTL/LiveTL#154]
When you click 'Blacklist User' on a Chat message, it will correctly update the user filter in the settings to show that the user is blacklisted, however, if the user is a channel moderator, messages they send will continue to show up (when the 'Show Mod Messages' option is enabled, if it's not, it woks as intended).

**Comment by r2dev2** [comment]
This is happening because two variables are declared in ``frame.js`` over [here](https://github.com/LiveTL/LiveTL/blob/c25f5ed3cd9688038352cb353ccc2c6d32d2b47f/LiveTL/js/frame.js#L40-L42). These two variables are being referred to in ``storage.js`` without being imported. They cannot be imported from ``frame.js`` as that would lead to a circular dependency, so the constants must be moved to ``web-constants.js`` or ``constants.js`` and imported.
