### ISSUE TITLE
embed not working in Vivaldi

### ISSUE THREAD

**Issue by stradus64** [LiveTL/LiveTL#332]
Embed function does not work on Vivaldi browser on waiting room and live stream, it does work correctly on VOD of a stream that has ended though.

To reproduce click "Embed TLs" button on page of upcoming or ongoing stream

Arch Linux
vivaldi 4.1.2369.21-1
![2021-08-28_21-00](https://user-images.githubusercontent.com/10760147/131228237-6794c622-bdec-4419-8c16-79d32108ea71.png)
![2021-08-28_21-02](https://user-images.githubusercontent.com/10760147/131228245-a3d7f9a5-4844-43b5-b5c7-00cd2e9e3e8f.png)

**Comment by ChrRubin** [comment]
This is a known bug with Chromium based browsers. It's one of those problems that just happens randomly with no real rhyme or reason that we can identify, and we're not sure if its a bug on our side or on Chromium's side, since it doesn't seem to affect Firefox.

Usually refreshing the page or toggling hide/show chat would fix it temporarily, but aside from that we'll need more investigation to figure out what's exactly causing this.

**Comment by KentoNishi** [comment]
closing because this problem hasn't been reported recently.
